CREATE TABLE `loan` (
	`id` INT(11) NOT NULL,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`category` VARCHAR(50) NULL DEFAULT NULL,
	`loanType` VARCHAR(50) NULL DEFAULT NULL,
	`loanAmount` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
